/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TRANSFER_H_RPCGEN
#define _TRANSFER_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>

#define MAXLEN 262144

typedef char filebytes[MAXLEN];
#ifdef __cplusplus
extern "C" bool_t xdr_filebytes(XDR *, filebytes);
#elif __STDC__
extern  bool_t xdr_filebytes(XDR *, filebytes);
#else /* Old Style C */
bool_t xdr_filebytes();
#endif /* Old Style C */


struct file {
	char name[MAXLEN];
	filebytes data;
	int nbytes;
};
typedef struct file file;
#ifdef __cplusplus
extern "C" bool_t xdr_file(XDR *, file*);
#elif __STDC__
extern  bool_t xdr_file(XDR *, file*);
#else /* Old Style C */
bool_t xdr_file();
#endif /* Old Style C */


#define TRANSFER ((rpc_uint)0x31230000)
#define TRANSFER_1 ((rpc_uint)1)

#ifdef __cplusplus
#define TRANSF ((rpc_uint)1)
extern "C" int * transf_1(file *, CLIENT *);
extern "C" int * transf_1_svc(file *, struct svc_req *);

#elif __STDC__
#define TRANSF ((rpc_uint)1)
extern  int * transf_1(file *, CLIENT *);
extern  int * transf_1_svc(file *, struct svc_req *);

#else /* Old Style C */
#define TRANSF ((rpc_uint)1)
extern  int * transf_1();
extern  int * transf_1_svc();
#endif /* Old Style C */

#endif /* !_TRANSFER_H_RPCGEN */
